#!/bin/sh

# Resolve asdf conflicts
echo "Overwriting files in $HOME"
yadm checkout $HOME

yadm_dir=$HOME/.config/yadm/

# create directories
source $yadm_dir/directories.sh

# install packages and apps from homebrew
source $yadm_dir/brew.sh

# install the latest version of nodejs
source $yadm_dir/nodejs.sh

# install the latest version of ruby
# install the latest version of rails
source $yadm_dir/ruby_on_rails.sh

# install rust (some neovim plugins use cargo)
source $yadm_dir/rust.sh

# setup zsh syntax highlighting and autosuggestions
source $yadm_dir/zsh.sh

# load iterm preferences
source $yadm_dir/iterm.sh

# setup neovim
source $yadm_dir/neovim.sh

# setup tmux
source $yadm_dir/tmux.sh

# set wallpaper
source $yadm_dir/wallpaper.sh

# setup mac preferences
source $yadm_dir/mac_preferences.sh

echo "Success"
