#!/bin/sh

# Resolve asdf conflicts
echo "Overwriting files in $HOME"
yadm checkout $HOME

yadm_dir=$HOME/.config/yadm

# install packages and apps from homebrew
source $yadm_dir/brew.sh

# install the latest version of nodejs
source $yadm_dir/nodejs.sh

# install latest yarn version
source $yadm_dir/yarn.sh

# install the latest version of ruby
# install the latest version of rails
source $yadm_dir/ruby.sh

# setup zsh syntax highlighting and autosuggestions
source $yadm_dir/zsh.sh

# load iterm preferences
source $yadm_dir/iterm.sh

# setup neovim
source $yadm_dir/neovim.sh

# setup tmux
source $yadm_dir/tmux.sh

# install tmuxinator
source $yadm_dir/tmuxinator.sh

echo "Success"
