#!/bin/sh

update_brew_packages(){
  if [ -f $HOME/.Brewfile ]; then
    echo "Installing packages from Brewfile"
    brew bundle --file=$HOME/.Brewfile
    . $(brew --prefix asdf)/libexec/asdf.sh
  else
}

resolve_asdf_conflicts(){
  echo "Overwriting conflicts in $HOME"
  yadm checkout $HOME
}

install_nodejs(){
  echo "\nInstalling nodejs"
  asdf plugin add nodejs
  asdf install nodejs latest 
  asdf global nodejs latest
}

install_ruby(){
  echo "\nInstalling ruby"
  asdf plugin add ruby
  asdf install ruby latest 
  asdf global ruby latest
}

install_rust(){
  echo "\nInstalling rust"
  asdf plugin add rust
  asdf install rust latest 
  asdf global rust latest
}

install_zsh_syntax_highlighting(){
  echo "\nInstalling zsh syntax highlighting"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
}

install_zsh_autosuggestions(){
  echo "\nInstalling zsh autosuggestions"
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
}

setup_iterm(){
  echo "\nSetting up iterm2"
  defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.iterm2"
  # load iterm2 preferences
  defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
}

install_jetBrains(){
  echo "\nInstalling JetBrainsMono Nerd Font"
  cd $HOME/Library/Fonts/
  curl -fLo "JetBrainsMono.zip" https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip
  unzip JetBrainsMono.zip
  rm JetBrains*Windows*
  rm JetBrainsMono.zip readme.md
  cd $HOME
}

adjust_keyboard_repeat_rate(){
  echo "\nAdjusting keyboard repeat rate"
  defaults write -g InitialKeyRepeat -int 10
  defaults write -g KeyRepeat -int 1
}


setup_neovim(){
  echo "\nInstalling tree-sitter-cli"
  npm install --global tree-sitter-cli

  echo "\nSetting up neovim"
  rm -rf $HOME/.local/share/nvim
  rm -rf $HOME/.config/nvim/plugin
  git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  nvim --headless -c 'MasonInstall prettierd stylua' -c 'quitall'
}

setup_tmux(){
  echo "\nSetting up Tmux"
  # install tpm
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  # start a server but don't attach to it
  tmux start-server
  # create a new session but don't attach to it either
  tmux new-session -d
  # install the plugins
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  tmux kill-server
}

create_projects_dir(){
  mkdir -p -v $HOME/Projects
}

resolve_asdf_conflicts
update_brew_packages
install_nodejs
install_ruby
install_rust
install_zsh_syntax_highlighting
install_zsh_autosuggestions
setup_iterm
install_jetBrains
adjust_keyboard_repeat_rate
setup_neovim
setup_tmux
create_projects_dir

echo "Success"
